export const BITESHOOTER_MAX_HEALTH = 100;
export const BITESHOOTER_INNER_DAMAGE = 3;
export const BITESHOOTER_MIDDLE_DAMAGE = 2;
export const BITESHOOTER_OUTER_DAMAGE = 1;

export const BITESHOOTER_COUNTDOWN_MS = 3_000;
export const BITESHOOTER_MATCH_TIMEOUT_MS = 60_000;
export const BITESHOOTER_CHALLENGE_TTL_MS = 60_000;
export const BITESHOOTER_LOBBY_TIMEOUT_MS = 60_000;
export const BITESHOOTER_TARGET_OUTER_DIAMETER_DESKTOP = 72;
export const BITESHOOTER_TARGET_OUTER_DIAMETER_MOBILE = 64;
export const BITESHOOTER_MIDDLE_RADIUS_RATIO = 0.62;
export const BITESHOOTER_INNER_RADIUS_RATIO = 0.3;
export const BITESHOOTER_TARGET_EDGE_PADDING = 12;
/** Logical radius used for server-authored normalized hit coordinates. */
export const BITESHOOTER_CANONICAL_OUTER_RADIUS = 0.04;

export const BITESHOOTER_BOT_INTERVAL_MS = 700;
